-- ALTER TABLE REGION DROP CONSTRAINT REGION_PKEY CASCADE;
-- ALTER TABLE NATION DROP CONSTRAINT NATION_PKEY CASCADE;
-- ALTER TABLE PART DROP CONSTRAINT PART_PKEY CASCADE;
-- ALTER TABLE SUPPLIER DROP CONSTRAINT SUPPLIER_PKEY CASCADE;
-- ALTER TABLE PARTSUPP DROP CONSTRAINT PARTSUPP_PKEY CASCADE;
-- ALTER TABLE ORDERS DROP CONSTRAINT ORDERS_PKEY CASCADE;
-- ALTER TABLE LINEITEM DROP CONSTRAINT LINEITEM_PKEY CASCADE;
-- ALTER TABLE CUSTOMER DROP CONSTRAINT CUSTOMER_PKEY CASCADE;

ALTER TABLE NATION DROP CONSTRAINT nation_n_regionkey_fkey;
ALTER TABLE SUPPLIER DROP CONSTRAINT supplier_s_nationkey_fkey;
ALTER TABLE CUSTOMER DROP CONSTRAINT customer_c_nationkey_fkey;
ALTER TABLE PARTSUPP DROP CONSTRAINT partsupp_ps_suppkey_fkey;
ALTER TABLE PARTSUPP DROP CONSTRAINT partsupp_ps_partkey_fkey;
ALTER TABLE ORDERS DROP CONSTRAINT orders_o_custkey_fkey;
ALTER TABLE LINEITEM DROP CONSTRAINT lineitem_l_orderkey_fkey;
ALTER TABLE LINEITEM DROP CONSTRAINT lineitem_l_partkey_fkey;
