ALTER TABLE REGION DROP CONSTRAINT REGION_PKEY;
ALTER TABLE NATION DROP CONSTRAINT NATION_PKEY;
ALTER TABLE PART DROP CONSTRAINT PART_PKEY;
ALTER TABLE SUPPLIER DROP CONSTRAINT SUPPLIER_PKEY;
ALTER TABLE PARTSUPP DROP CONSTRAINT PARTSUPP_PKEY;
ALTER TABLE ORDERS DROP CONSTRAINT ORDERS_PKEY;
ALTER TABLE LINEITEM DROP CONSTRAINT LINEITEM_PKEY;
ALTER TABLE CUSTOMER DROP CONSTRAINT CUSTOMER_PKEY;
