ALTER TABLE REGION DROP CONSTRAINT REGION_PKEY CASCADE;
ALTER TABLE NATION DROP CONSTRAINT NATION_PKEY CASCADE;
ALTER TABLE PART DROP CONSTRAINT PART_PKEY CASCADE;
ALTER TABLE SUPPLIER DROP CONSTRAINT SUPPLIER_PKEY CASCADE;
ALTER TABLE PARTSUPP DROP CONSTRAINT PARTSUPP_PKEY CASCADE;
ALTER TABLE ORDERS DROP CONSTRAINT ORDERS_PKEY CASCADE;
ALTER TABLE LINEITEM DROP CONSTRAINT LINEITEM_PKEY CASCADE;
ALTER TABLE CUSTOMER DROP CONSTRAINT CUSTOMER_PKEY CASCADE;
