SELECT COUNT(*) FROM CUSTOMER;
SELECT COUNT(*) FROM LINEITEM;
SELECT COUNT(*) FROM NATION;
SELECT COUNT(*) FROM ORDERS;
SELECT COUNT(*) FROM PART;
SELECT COUNT(*) FROM PARTSUPP;
SELECT COUNT(*) FROM REGION;
SELECT COUNT(*) FROM SUPPLIER;
